import { test,expect } from '@playwright/test';
test('complete frontend Stage 0 journey',async({page})=>{
 await page.goto('/login');await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByRole('heading',{name:/this week/i})).toBeVisible();
 await page.getByRole('link',{name:'Settings'}).click();await page.getByLabel('Dietary patterns').fill('flexitarian, Mediterranean');await page.getByLabel('Preferences and constraints').fill('Fast weekday meals');await page.getByRole('button',{name:'Save dietary profile'}).click();await expect(page.getByRole('status')).toContainText('Dietary preferences updated');
 await page.getByRole('link',{name:'Ingredients'}).click();await page.getByRole('button',{name:'Create ingredient'}).click();await page.getByLabel('Name').fill('Fresh Basil');await page.getByLabel('Default unit').fill('bunches');await page.getByRole('button',{name:'Save ingredient'}).click();await expect(page.getByText('Fresh Basil')).toBeVisible();await page.getByText('Fresh Basil').locator('..').getByRole('button',{name:'Edit'}).click();
 await page.getByRole('link',{name:'Recipes'}).click();await page.getByRole('button',{name:'Create recipe'}).click();await page.getByLabel('Name').fill('Basil Pasta Bowl');await page.getByLabel('Description').fill('A complete fresh basil pasta dinner.');await page.getByLabel('Cuisine').fill('Italian');await page.getByLabel('Step 1').fill('Cook and combine all ingredients.');await page.getByRole('button',{name:'Save recipe'}).click();await expect(page.getByText('Basil Pasta Bowl')).toBeVisible();
 await page.getByRole('link',{name:'Meal plans'}).click();await page.getByRole('button',{name:'Create plan'}).click();await page.getByLabel('Plan name').fill('E2E week');await page.getByRole('button',{name:'Save plan'}).click();await page.getByText('E2E week').locator('..').getByRole('button',{name:'Add meal'}).click();await page.getByLabel('Recipe').selectOption({label:'Basil Pasta Bowl'});await page.getByRole('button',{name:'Save meal'}).click();
 await page.getByRole('link',{name:'Shopping'}).click();await page.getByLabel('Source plan').selectOption({label:'E2E week'});await page.getByRole('button',{name:/generate list/i}).click();await page.getByLabel('Manual item').fill('Coffee');await page.getByRole('button',{name:'Add manual item'}).click();await expect(page.getByText(/Coffee/)).toBeVisible();
 await page.getByRole('link',{name:'Household'}).click();await page.getByLabel('Email').fill('e2e-invite@example.com');await page.getByRole('button',{name:'Invite'}).click();await expect(page.getByText(/e2e-invite@example.com/)).toBeVisible();
 await page.getByRole('link',{name:'Settings'}).click();await page.getByRole('button',{name:'Reset dummy data'}).click();await expect(page.getByRole('heading',{name:/sign in/i})).toBeVisible();
});
