"""Adding ingredients"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002_ingredients"
down_revision: str | None = "0001_supporting_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "produce",
                "meat_and_poultry",
                "seafood",
                "dairy",
                "grains",
                "legumes",
                "spices",
                "condiments",
                "baking",
                "other",
                name="ingredient_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "default_unit",
            sa.Enum("grams", "kilograms", "milliliters", "liters", "units", name="ingredient_unit"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.Enum("active", "archived", name="ingredient_status"), nullable=False
        ),
        sa.Column("allergens", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name", name="uq_ingredient"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingredients")

    sa.Enum(name="ingredient_category").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="ingredient_unit").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="ingredient_status").drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
